// 
// Copyright (c) 2022 by Cisco Systems, Inc.
// All rights reserved.
//
// This file was generated by gen_Fw_utilConfig.py
// Do not modify!
//

#include <string>

namespace facebook::fboss::platform {

std::string getLassenFpdsData() {
  return R"json({
    "fpds": [
        {
            "cmdline": [
                "/opt/cisco/bin/bios_upgrade.sh",
                "{PATH}"
            ],
            "description": "BIOS - Basic Input Output System",
            "dllpath": "/opt/cisco/lib/libfpd_bios.so.1.0.1",
            "dllsymbol": "get_fpd_obj_bios",
            "image_ext_name": "spf-ns-bios-upgrade.img",
            "match": [],
            "name": "BIOS",
            "offsets": {
                "uio_block_name": "VLTN-SOC"
            },
            "oid": {
                "index": 1,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/spf-ns-bios-upgrade.img"
        },
        {
            "cmdline": [
                "/opt/cisco/bin/bios_upgrade.sh",
                "{PATH}",
                "{PATH}"
            ],
            "description": "BIOS - Basic Input Output System",
            "dllpath": "/opt/cisco/lib/libfpd_bios.so.1.0.1",
            "dllsymbol": "get_fpd_obj_bios",
            "golden": true,
            "match": [],
            "name": "BIOS_GOLDEN",
            "offsets": {
                "flash_version_offset": "0xDA8E00",
                "uio_block_name": "VLTN-SOC"
            },
            "oid": {
                "index": 2,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/spf_ns_bios_golden_upgrade.img"
        },
        {
            "cmdline": "/opt/cisco/bin/fpd_sjtag_iofpga_update.sh",
            "description": "Omega FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "fw_ver_path": "/sys/bus/platform/devices/info.1/version",
            "image_ext_name": "sonic_rp_iofpga_sjtag_fpd.img",
            "match": [],
            "name": "IOFPGA_SJTAG",
            "offsets": {
                "image_offset": "0x1000000",
                "image_size": "0xF80000",
                "mdata_offset": "0x1F80000",
                "mdata_size": "0x10000",
                "uio_block_name": "IOFP-JTAG"
            },
            "oid": {
                "index": 3,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/sonic_rp_iofpga_sjtag_fpd.img"
        },
        {
            "alt_path": "/opt/cisco/fpd/sf_fixed_1ru_valentine_x86_tam_fw_upgrade.img",
            "description": "Aikido - x86 FPGA",
            "dllpath": "/opt/cisco/lib/libfpd_aikido.so.1.0.1",
            "dllsymbol": "get_fpd_obj_aikido",
            "fw_ver_path": "/sys/bus/platform/devices/info.0/version",
            "image_ext_name": "sf_fixed_1ru_valentine_x86_aikido_upgrade.img",
            "match": [],
            "name": "AIKIDO",
            "offsets": {
                "fpga_img_offset": "0x961000",
                "fpga_mdata_offset": "0xFEB000",
                "tam_fw_offset": "0x280000",
                "tam_mdata_offset": "0xFE9000"
            },
            "oid": {
                "index": 4,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/sf_fixed_1ru_valentine_x86_aikido_upgrade.img"
        },
        {
            "description": "TAM FW - x86",
            "dllpath": "/opt/cisco/lib/libfpd_tam_util.so.1.0.1",
            "dllsymbol": "get_fpd_obj_tam",
            "match": [],
            "name": "TAM",
            "oid": {
                "index": 5,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/sf_fixed_1ru_valentine_x86_tam_fw_upgrade.img"
        },
        {
            "description": "SSD",
            "dllpath": "/opt/cisco/lib/libfpd_ssd.so.1.0.1",
            "dllsymbol": "get_fpd_obj_ssd",
            "image_ext_name": "ssdfw_intel_s4510.img",
            "match": [],
            "name": "SSD",
            "oid": {
                "index": 6,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/ssd/ssdfw_intel_s4510.img"
        },
        {
            "cmdline": [
                "/opt/cisco/bin/fpd_powercpld.sh",
                "{PATH}",
                "{PATH}"
            ],
            "description": "Power CPLD",
            "dllpath": "/opt/cisco/lib/libfpd_pwrcpld.so.1.0.1",
            "dllsymbol": "get_fpd_obj_pwrcpld",
            "fw_ver_path": "[i2c:IO-MUX-4:0x77]/cpld_version",
            "image_ext_name": "churchillPwrCpld_top_upgrade.img",
            "match": [],
            "name": "POWER_CPLD",
            "oid": {
                "index": 7,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/power_cpld/churchillPwrCpld_top_upgrade.img"
        },
        {
            "alt_path": "/opt/cisco/fpd/cpu_cpld/bundle_lattice_machx03_cpu_cpld_i2c_churchill_bmc_upgrade.img",
            "description": "CPU CPLD",
            "device_path": "[i2c:X86-MUX-0:0x40]/",
            "dllpath": "/opt/cisco/lib/libfpd_cpucpld.so.1.0.1",
            "dllsymbol": "get_fpd_obj_cpucpld",
            "fw_ver_path": "/sys/bus/platform/devices/msd/status4",
            "image_ext_name": "bundle_lattice_machx03_cpu_cpld_i2c_churchill_bmc.bin",
            "match": [],
            "name": "CPU_CPLD",
            "oid": {
                "index": 8,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/cpu_cpld/bundle_lattice_machx03_cpu_cpld_i2c_churchill_bmc.bin"
        },
        {
            "activate_path": "[i2c:IO-MUX-6:0x53]/hwmon/hwmon*/power_cycle_cpld",
            "alt_path": "/opt/cisco/fpd/pem_cpld/bundle_lattice_machx03_pem_cpld_i2c_upgrade.img",
            "description": "PEM0 CPLD",
            "device_path": "[i2c:IO-MUX-6:0x54]/",
            "dllpath": "/opt/cisco/lib/libfpd_pemcpld.so.1.0.1",
            "fw_ver_path": "[i2c:IO-MUX-6:0x53]/hwmon/hwmon*/cpld_revision",
            "image_ext_name": "bundle_lattice_machx03_pem_cpld_i2c.bin",
            "match": [
                [
                    "idprom",
                    "PSU0",
                    "PCB_PARTNBR_6",
                    "073-20765-0[23]"
                ]
            ],
            "name": "PEM_CPLD",
            "oid": {
                "index": 9,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 4,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/pem_cpld/bundle_lattice_machx03_pem_cpld_i2c.bin"
        },
        {
            "activate_path": "[i2c:IO-MUX-7:0x53]/hwmon/hwmon*/power_cycle_cpld",
            "alt_path": "/opt/cisco/fpd/pem_cpld/bundle_lattice_machx03_pem_cpld_i2c_upgrade.img",
            "description": "PEM1 CPLD",
            "device_path": "[i2c:IO-MUX-7:0x54]/",
            "dllpath": "/opt/cisco/lib/libfpd_pemcpld.so.1.0.1",
            "fw_ver_path": "[i2c:IO-MUX-7:0x53]/hwmon/hwmon*/cpld_revision",
            "image_ext_name": "bundle_lattice_machx03_pem_cpld_i2c.bin",
            "match": [
                [
                    "idprom",
                    "PSU1",
                    "PCB_PARTNBR_6",
                    "073-20765-0[23]"
                ]
            ],
            "name": "PEM_CPLD",
            "oid": {
                "index": 10,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 9,
                    "type": "psu_tray"
                },
                {
                    "index": 6,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/pem_cpld/bundle_lattice_machx03_pem_cpld_i2c.bin"
        }
    ],
    "pid": "8101_32FH_O_BMC"
}
  )json";

} // getLassenFpds()

} // namespace facebook::fboss::platform
