// 
// Copyright (c) 2022 by Cisco Systems, Inc.
// All rights reserved.
//
// This file was generated by gen_Fw_utilConfig.py
// Do not modify!
//

#include <string>

namespace facebook::fboss::platform {

std::string getSandiaFpdsData() {
  return R"json({
    "fpds": [
        {
            "cmdline": [
                "/opt/cisco/bin/bios_upgrade.sh",
                "{PATH}"
            ],
            "description": "BIOS - Basic Input Output System",
            "dllpath": "/opt/cisco/lib/libfpd_bios.so.1.0.1",
            "dllsymbol": "get_fpd_obj_bios",
            "expected_version": "0.34",
            "match": [],
            "name": "BIOS",
            "offsets": {
                "uio_block_name": "PXSX-SOC"
            },
            "oid": {
                "index": 1,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/bios/spf_scm_bios_upgrade.img"
        },
        {
            "cmdline": [
                "/opt/cisco/bin/bios_upgrade.sh",
                "{PATH}",
                "{PATH}"
            ],
            "description": "BIOS - Basic Input Output System",
            "dllpath": "/opt/cisco/lib/libfpd_bios.so.1.0.1",
            "dllsymbol": "get_fpd_obj_bios",
            "expected_version": "0.34",
            "golden": true,
            "match": [],
            "name": "BIOS_GOLDEN",
            "offsets": {
                "flash_version_offset": "0xDACE00",
                "uio_block_name": "PXSX-SOC"
            },
            "oid": {
                "index": 2,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/bios/spf_scm_bios_golden_upgrade.img"
        },
        {
            "alias": [
                "scm"
            ],
            "alt_path": "/opt/cisco/fpd/x86fpga/sf_central_x86_tam_fw_cyclonus_kodiak_upgrade.img",
            "description": "Aikido - x86 FPGA",
            "dllpath": "/opt/cisco/lib/libfpd_aikido.so.1.0.1",
            "dllsymbol": "get_fpd_obj_aikido",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/info.0/version",
            "match": [],
            "name": "AIKIDO",
            "offsets": {
                "fpga_img_offset": "0x591000",
                "fpga_mdata_offset": "0x84B000",
                "tam_fw_offset": "0x280000",
                "tam_mdata_offset": "0x849000"
            },
            "oid": {
                "index": 3,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/x86fpga/sf_central_x86_aikido_cyclonus_kodiak_upgrade.img"
        },
        {
            "alt_path": "/opt/cisco/fpd/x86fpga/sf_central_x86_tam_fw_cyclonus_kodiak_golden.img",
            "description": "Aikido - x86 FPGA",
            "dllpath": "/opt/cisco/lib/libfpd_aikido.so.1.0.1",
            "dllsymbol": "get_fpd_obj_aikido",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "AIKIDO_GOLDEN",
            "offsets": {
                "fpga_img_offset": "0x301000",
                "fpga_mdata_offset": "0x84A000",
                "tam_fw_offset": "0x210000",
                "tam_mdata_offset": "0x848000"
            },
            "oid": {
                "index": 4,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/x86fpga/sf_central_x86_aikido_cyclonus_kodiak_golden.img"
        },
        {
            "description": "TAM FW - x86",
            "dllpath": "/opt/cisco/lib/libfpd_tam_util.so.1.0.1",
            "dllsymbol": "get_fpd_obj_tam",
            "expected_version": "7.12",
            "match": [],
            "name": "TAM",
            "oid": {
                "index": 5,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/x86fpga/sf_central_x86_tam_fw_cyclonus_kodiak_upgrade.img"
        },
        {
            "activate_path": "/sys/class/nvme/nvme0/device/reset",
            "alias": [
                "ssd"
            ],
            "cmdline": [
                "/opt/cisco/bin/nvme_upgrade.sh",
                "{PATH}"
            ],
            "description": "NVMe SSD",
            "dllpath": "/opt/cisco/lib/libfpd_nvme.so.1.0.1",
            "dllsymbol": "get_fpd_obj_nvme",
            "expected_version": "",
            "match": [],
            "name": "NVME",
            "oid": {
                "index": 6,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/nvme.imgs"
        },
        {
            "description": "CPU CPLD",
            "device_path": "/run/devmap/cplds/CPU_CPLD_UPGRADE",
            "dllpath": "/opt/cisco/lib/libfpd_cpucpld.so.1.0.1",
            "dllsymbol": "get_fpd_obj_cpucpld",
            "expected_version": "0.32",
            "fw_ver_path": "/sys/bus/platform/devices/msd/status4",
            "match": [],
            "name": "CPU_CPLD",
            "offsets": {
                "version_block_addr": "0x12000",
                "version_mask": "0x3F000000",
                "version_reg_offset": "0x3C",
                "version_reg_shift": "24"
            },
            "oid": {
                "index": 7,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/cpu_cpld/bundle_lattice_machx03_cpu_cpld_i2c_kodiak_bmc.bin"
        },
        {
            "cmdline": [
                "/opt/cisco/bin/fpd_powercpld.sh",
                "{PATH}",
                "{PATH}"
            ],
            "description": "POWER CPLD",
            "dllpath": "/opt/cisco/lib/libfpd_pwrcpld.so.1.0.1",
            "dllsymbol": "get_fpd_obj_pwrcpld",
            "expected_version": "0.15",
            "match": [],
            "name": "POWER_CPLD",
            "offsets": {
                "version_block_addr": "0x12000",
                "version_mask": "0x3F0000",
                "version_reg_offset": "0x3C",
                "version_reg_shift": "16"
            },
            "oid": {
                "index": 8,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/power_cpld/sf_smb_power_cpld_upgrade.bin"
        },
        {
            "alias": [
                "smb"
            ],
            "description": "Silverbolt FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.0",
            "fw_ver_path": "/sys/bus/platform/devices/info.1/version",
            "match": [],
            "name": "SMB_IOFPGA",
            "offsets": {
                "image_offset": "0x1000000",
                "image_size": "0xFC0000",
                "mdata_offset": "0x1FC0000",
                "mdata_size": "0x40000",
                "uio_block_name": "IOFP-SPI0"
            },
            "oid": {
                "index": 9,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_smb_silverbolt_iofpga_kodiak_upgrade.img"
        },
        {
            "alias": [
                "smb_golden"
            ],
            "description": "Silverbolt FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.0",
            "golden": true,
            "match": [],
            "name": "SMB_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x0",
                "image_size": "0xFC0000",
                "mdata_offset": "0xFC0000",
                "mdata_size": "0x40000",
                "uio_block_name": "IOFP-SPI0"
            },
            "oid": {
                "index": 10,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_smb_silverbolt_iofpga_kodiak_golden.img"
        },
        {
            "alias": [
                "pim",
                "pim1"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.1/info-pim1/version",
            "match": [],
            "name": "PIM1_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "1"
            },
            "oid": {
                "index": 11,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.1/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim1_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM1_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "1"
            },
            "oid": {
                "index": 12,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.1/pim_ready"
        },
        {
            "alias": [
                "pim",
                "pim2"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.2/info-pim2/version",
            "match": [],
            "name": "PIM2_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "2"
            },
            "oid": {
                "index": 13,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 2,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.2/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim2_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM2_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "2"
            },
            "oid": {
                "index": 14,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 2,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.2/pim_ready"
        },
        {
            "alias": [
                "pim",
                "pim3"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.3/info-pim3/version",
            "match": [],
            "name": "PIM3_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "3"
            },
            "oid": {
                "index": 15,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 3,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.3/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim3_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM3_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "3"
            },
            "oid": {
                "index": 16,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 3,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.3/pim_ready"
        },
        {
            "alias": [
                "pim",
                "pim4"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.4/info-pim4/version",
            "match": [],
            "name": "PIM4_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "4"
            },
            "oid": {
                "index": 17,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 4,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.4/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim4_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM4_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "4"
            },
            "oid": {
                "index": 18,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 4,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.4/pim_ready"
        },
        {
            "alias": [
                "pim",
                "pim5"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.5/info-pim5/version",
            "match": [],
            "name": "PIM5_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "5"
            },
            "oid": {
                "index": 19,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 5,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.5/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim5_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM5_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "5"
            },
            "oid": {
                "index": 20,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 5,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.5/pim_ready"
        },
        {
            "alias": [
                "pim",
                "pim6"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.6/info-pim6/version",
            "match": [],
            "name": "PIM6_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "6"
            },
            "oid": {
                "index": 21,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 6,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.6/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim6_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM6_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "6"
            },
            "oid": {
                "index": 22,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 6,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.6/pim_ready"
        },
        {
            "alias": [
                "pim",
                "pim7"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.7/info-pim7/version",
            "match": [],
            "name": "PIM7_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "7"
            },
            "oid": {
                "index": 23,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 7,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.7/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim7_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM7_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "7"
            },
            "oid": {
                "index": 24,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 7,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.7/pim_ready"
        },
        {
            "alias": [
                "pim",
                "pim8"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "fw_ver_path": "/sys/bus/platform/devices/slpc-m-slot.8/info-pim8/version",
            "match": [],
            "name": "PIM8_IOFPGA",
            "offsets": {
                "image_offset": "0x800000",
                "image_size": "0x7F8000",
                "mdata_offset": "0xFFF000",
                "mdata_size": "0x1000",
                "uio_block_name": "8"
            },
            "oid": {
                "index": 25,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 8,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_upgrade.img",
            "presence": "/sys/bus/platform/devices/slpc-m.8/pim_ready"
        },
        {
            "alias": [
                "pim_golden",
                "pim8_golden"
            ],
            "description": "Pinpointer FPGA - Xilinx",
            "dllpath": "/opt/cisco/lib/libfpd_sjtag.so.1.0.1",
            "dllsymbol": "get_fpd_obj_sjtag",
            "expected_version": "1.2",
            "golden": true,
            "match": [],
            "name": "PIM8_IOFPGA_GOLDEN",
            "offsets": {
                "image_offset": "0x000000",
                "image_size": "0x7FF000",
                "mdata_offset": "0x7FF000",
                "mdata_size": "0x1000",
                "uio_block_name": "8"
            },
            "oid": {
                "index": 26,
                "type": "fpd"
            },
            "parents": [
                {
                    "index": 8,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "/opt/cisco/fpd/iofpga/sf_pim_pinpointer_iofpga_kodiak_golden.img",
            "presence": "/sys/bus/platform/devices/slpc-m.8/pim_ready"
        }
    ],
    "pid": "85_SCM_O_BMC"
}
  )json";

} // getSandiaFpds()

} // namespace facebook::fboss::platform
