// 
// Copyright (c) 2022 by Cisco Systems, Inc.
// All rights reserved.
//
// This file was generated by gen_WeutilConfig.py
// Do not modify!
//

#include <string>

namespace facebook::fboss::platform {

std::string getLassenIdpromsData() {
  return R"json({
    "idproms": [
        {
            "aliases": [
                "idprom",
                "bootstrap",
                "Base_Board_IDPROM",
                "chassis",
                "Chassis_IDPROM",
                "MB_IDPROM"
            ],
            "computed_fields": {
                "CPU_POL": {
                    "bits": [
                        27
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS",
                    "values": {
                        "0": "IR",
                        "1": "TI"
                    }
                },
                "GB_CORE_VOLTAGE": {
                    "bits": [
                        53,
                        52
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS",
                    "values": {
                        "0": "0.75 V",
                        "1": "0.80 V",
                        "2": "0.825 V"
                    }
                },
                "GB_IDENTIFIER": {
                    "bits": [
                        26,
                        25,
                        63,
                        62,
                        61
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS",
                    "values": {
                        "10": "A2 12.8T Recovered",
                        "13": "13:illegal [A2 3.2T CR1]\"",
                        "14": "6:illegal [A2 3.2T CR2]\"",
                        "18": "18:illegal [A2 6.4T Fully Tested]",
                        "2": "A2 12.8T",
                        "26": "26:illegal [A2 6.4T Recovered]\"",
                        "5": "5:illegal [A1 3.2T CR1]\"",
                        "6": "6:illegal [A1 3.2T CR2]\""
                    }
                },
                "GB_PRESENT": {
                    "bits": [
                        60
                    ],
                    "default": "Not Mounted",
                    "from": "DEVICE_VALS",
                    "values": {
                        "0": "Mounted",
                        "1": "Not Mounted"
                    }
                },
                "GB_REVISION": {
                    "bits": [
                        63,
                        62,
                        61
                    ],
                    "default": "A0",
                    "from": "DEVICE_VALS",
                    "values": {
                        "0": "A0",
                        "1": "A1",
                        "2": "A2",
                        "3": "3:illegal [Matilda A1 6.4T]",
                        "4": "A1 Recovered",
                        "5": "5:illegal [M32 A1 3.2T CR-1 (slice 0,1,2)]",
                        "6": "6:illegal [M32 3.2T CR-2 (slice 3,4,5)]",
                        "7": "7:illegal [M32 6.4T A1]"
                    }
                },
                "HBM": {
                    "bits": [
                        59,
                        58,
                        57,
                        56
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS",
                    "values": {
                        "0": "0:illegal [Samsung B-die (Pacific)]",
                        "1": "1:illegal [Samsung X-die (Pacific)]",
                        "2": "GB 2.5D HBM without MACsec",
                        "3": "GB Mono without MACsec"
                    }
                },
                "IOFPGA_DEVICE": {
                    "bits": [
                        35
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS",
                    "values": {
                        "0": "75T",
                        "1": "100T"
                    }
                },
                "MB_JMAC_CONTROLLER_VENDOR": {
                    "bits": [
                        29,
                        28
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS",
                    "values": {
                        "0": "Infineon IR35215",
                        "1": "TI TPS53681"
                    }
                },
                "SILAB_IMAGE": {
                    "bits": [
                        37,
                        36
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS"
                },
                "ZARLINK_IMAGE": {
                    "bits": [
                        39,
                        38
                    ],
                    "default": "Unknown",
                    "from": "DEVICE_VALS"
                }
            },
            "match": [],
            "name": "board",
            "oid": {
                "index": 1,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:IO-MUX-0:0x50]/eeprom",
            "size": 512
        },
        {
            "match": [],
            "name": "U57.CH7.EEP1",
            "oid": {
                "index": 2,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:X86-MUX-7:0x50]/eeprom"
        },
        {
            "aliases": [
                "MEZZ_IO_IDPROM"
            ],
            "match": [],
            "name": "mezz_io",
            "oid": {
                "index": 3,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:IO-MUX-1:0x50]/eeprom"
        },
        {
            "aliases": [
                "psu",
                "power"
            ],
            "match": [],
            "name": "PSU0",
            "oid": {
                "index": 4,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:IO-MUX-6:0x50]/eeprom"
        },
        {
            "aliases": [
                "psu",
                "power"
            ],
            "match": [],
            "name": "PowerBoard0",
            "oid": {
                "index": 5,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:IO-MUX-6:0x52]/eeprom"
        },
        {
            "aliases": [
                "psu",
                "power"
            ],
            "match": [],
            "name": "PSU1",
            "oid": {
                "index": 6,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 6,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:IO-MUX-7:0x50]/eeprom"
        },
        {
            "aliases": [
                "psu",
                "power"
            ],
            "match": [],
            "name": "PowerBoard1",
            "oid": {
                "index": 7,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 6,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:IO-MUX-7:0x52]/eeprom"
        },
        {
            "aliases": [
                "fan",
                "cooling"
            ],
            "fallback": {
                "PORT-SIDE-EXHAUST": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PE-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-50316-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Exhaust Ver 2"
                },
                "PORT-SIDE-INTAKE": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PI-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-49985-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Intake Ver 2"
                }
            },
            "fallback_algorithm": "w1",
            "fallback_presence": "/run/devmap/cisco/devices/FANTRAY1/fallback_presence",
            "fallback_status": "/run/devmap/cisco/devices/FANTRAY1/fallback_status",
            "match": [],
            "name": "fantray1",
            "oid": {
                "index": 8,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 3,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[w1:6:23-6]/eeprom"
        },
        {
            "aliases": [
                "fan",
                "cooling"
            ],
            "fallback": {
                "PORT-SIDE-EXHAUST": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PE-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-50316-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Exhaust Ver 2"
                },
                "PORT-SIDE-INTAKE": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PI-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-49985-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Intake Ver 2"
                }
            },
            "fallback_algorithm": "w1",
            "fallback_presence": "/run/devmap/cisco/devices/FANTRAY2/fallback_presence",
            "fallback_status": "/run/devmap/cisco/devices/FANTRAY2/fallback_status",
            "match": [],
            "name": "fantray2",
            "oid": {
                "index": 9,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 4,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[w1:5:23-5]/eeprom"
        },
        {
            "aliases": [
                "fan",
                "cooling"
            ],
            "fallback": {
                "PORT-SIDE-EXHAUST": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PE-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-50316-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Exhaust Ver 2"
                },
                "PORT-SIDE-INTAKE": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PI-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-49985-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Intake Ver 2"
                }
            },
            "fallback_algorithm": "w1",
            "fallback_presence": "/run/devmap/cisco/devices/FANTRAY3/fallback_presence",
            "fallback_status": "/run/devmap/cisco/devices/FANTRAY3/fallback_status",
            "match": [],
            "name": "fantray3",
            "oid": {
                "index": 10,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 5,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[w1:4:23-4]/eeprom"
        },
        {
            "aliases": [
                "fan",
                "cooling"
            ],
            "fallback": {
                "PORT-SIDE-EXHAUST": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PE-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-50316-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Exhaust Ver 2"
                },
                "PORT-SIDE-INTAKE": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PI-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-49985-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Intake Ver 2"
                }
            },
            "fallback_algorithm": "w1",
            "fallback_presence": "/run/devmap/cisco/devices/FANTRAY4/fallback_presence",
            "fallback_status": "/run/devmap/cisco/devices/FANTRAY4/fallback_status",
            "match": [],
            "name": "fantray4",
            "oid": {
                "index": 11,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 6,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[w1:3:23-3]/eeprom"
        },
        {
            "aliases": [
                "fan",
                "cooling"
            ],
            "fallback": {
                "PORT-SIDE-EXHAUST": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PE-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-50316-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Exhaust Ver 2"
                },
                "PORT-SIDE-INTAKE": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PI-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-49985-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Intake Ver 2"
                }
            },
            "fallback_algorithm": "w1",
            "fallback_presence": "/run/devmap/cisco/devices/FANTRAY5/fallback_presence",
            "fallback_status": "/run/devmap/cisco/devices/FANTRAY5/fallback_status",
            "match": [],
            "name": "fantray5",
            "oid": {
                "index": 12,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 7,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[w1:2:23-2]/eeprom"
        },
        {
            "aliases": [
                "fan",
                "cooling"
            ],
            "fallback": {
                "PORT-SIDE-EXHAUST": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PE-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-50316-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Exhaust Ver 2"
                },
                "PORT-SIDE-INTAKE": {
                    "CONTROLLER_TYPE": "1706",
                    "GROUP_TYPE": "148",
                    "PRODUCT_ID": "FAN-1RU-PI-V2",
                    "PWR_CONSUMPTION": "26.8",
                    "TOP_ASSY_PN_6": "800-49985-01",
                    "UDI_DESC": "Cisco 8000 Series 1RU Fan with Port-side Air Intake Ver 2"
                }
            },
            "fallback_algorithm": "w1",
            "fallback_presence": "/run/devmap/cisco/devices/FANTRAY6/fallback_presence",
            "fallback_status": "/run/devmap/cisco/devices/FANTRAY6/fallback_status",
            "match": [],
            "name": "fantray6",
            "oid": {
                "index": 13,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 8,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[w1:1:23-1]/eeprom"
        }
    ],
    "pid": "8101_32FH_O_BMC"
}
  )json";

} // getLassenIdproms()

} // namespace facebook::fboss::platform
