// 
// Copyright (c) 2022 by Cisco Systems, Inc.
// All rights reserved.
//
// This file was generated by gen_WeutilConfig.py
// Do not modify!
//

#include <string>

namespace facebook::fboss::platform {

std::string getSandiaIdpromsData() {
  return R"json({
    "idproms": [
        {
            "aliases": [
                "board",
                "idprom",
                "bootstrap",
                "Base_Board_IDPROM"
            ],
            "match": [],
            "name": "SCM",
            "oid": {
                "index": 1,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_IDPROM:0x50]/eeprom",
            "size": 512
        },
        {
            "aliases": [
                "chassis",
                "chassis_IDPROM",
                "Base_Board_IDPROM"
            ],
            "match": [],
            "name": "PDB",
            "oid": {
                "index": 2,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_IDPROM:0xa0d0]/eeprom",
            "size": 512
        },
        {
            "aliases": [
                "smb",
                "iob"
            ],
            "match": [],
            "name": "SMB",
            "oid": {
                "index": 3,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SMB_IDPROM:0x50]/eeprom",
            "size": 512
        },
        {
            "aliases": [
                "psu1",
                "pm1",
                "power1"
            ],
            "match": [],
            "name": "PSU1",
            "oid": {
                "index": 4,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_SMB_PSU:0xa050]/eeprom"
        },
        {
            "aliases": [
                "psu2",
                "pm2",
                "power2"
            ],
            "match": [],
            "name": "PSU2",
            "oid": {
                "index": 5,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 2,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_SMB_PSU:0xa0d0]/eeprom"
        },
        {
            "aliases": [
                "psu3",
                "pm3",
                "power3"
            ],
            "match": [],
            "name": "PSU3",
            "oid": {
                "index": 6,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 3,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_SMB_PSU:0xa150]/eeprom"
        },
        {
            "aliases": [
                "psu4",
                "pm4",
                "power4"
            ],
            "match": [],
            "name": "PSU4",
            "oid": {
                "index": 7,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 4,
                    "type": "psu_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_SMB_PSU:0xa1d0]/eeprom"
        },
        {
            "aliases": [
                "fan1"
            ],
            "match": [],
            "name": "fantray1",
            "oid": {
                "index": 8,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:FAN_IDPROM:0xa050]/eeprom"
        },
        {
            "aliases": [
                "fan2"
            ],
            "match": [],
            "name": "fantray2",
            "oid": {
                "index": 9,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 2,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:FAN_IDPROM:0xa0d0]/eeprom"
        },
        {
            "aliases": [
                "fan3"
            ],
            "match": [],
            "name": "fantray3",
            "oid": {
                "index": 10,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 3,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:FAN_IDPROM:0xa150]/eeprom"
        },
        {
            "aliases": [
                "fan4"
            ],
            "match": [],
            "name": "fantray4",
            "oid": {
                "index": 11,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 4,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:FAN_IDPROM:0xa1d0]/eeprom"
        },
        {
            "aliases": [
                "fan5"
            ],
            "match": [],
            "name": "fantray5",
            "oid": {
                "index": 12,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 5,
                    "type": "fan_tray"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:FAN_IDPROM:0xa250]/eeprom"
        },
        {
            "aliases": [
                "pim1"
            ],
            "match": [],
            "name": "PIM1",
            "oid": {
                "index": 13,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM1.IDPROM:0x50]/eeprom"
        },
        {
            "aliases": [
                "pim2"
            ],
            "match": [],
            "name": "PIM2",
            "oid": {
                "index": 14,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 2,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM2.IDPROM:0x50]/eeprom"
        },
        {
            "aliases": [
                "pim3"
            ],
            "match": [],
            "name": "PIM3",
            "oid": {
                "index": 15,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 3,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM3.IDPROM:0x50]/eeprom"
        },
        {
            "aliases": [
                "pim4"
            ],
            "match": [],
            "name": "PIM4",
            "oid": {
                "index": 16,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 4,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM4.IDPROM:0x50]/eeprom"
        },
        {
            "aliases": [
                "pim5"
            ],
            "match": [],
            "name": "PIM5",
            "oid": {
                "index": 17,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 5,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM5.IDPROM:0x50]/eeprom"
        },
        {
            "aliases": [
                "pim6"
            ],
            "match": [],
            "name": "PIM6",
            "oid": {
                "index": 18,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 6,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM6.IDPROM:0x50]/eeprom"
        },
        {
            "aliases": [
                "pim7"
            ],
            "match": [],
            "name": "PIM7",
            "oid": {
                "index": 19,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 7,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM7.IDPROM:0x50]/eeprom"
        },
        {
            "aliases": [
                "pim8"
            ],
            "match": [],
            "name": "PIM8",
            "oid": {
                "index": 20,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 8,
                    "type": "pim"
                },
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:PIM8.IDPROM:0x50]/eeprom"
        }
    ],
    "pid": "85_SCM_O_BMC"
}
  )json";

} // getSandiaIdproms()

} // namespace facebook::fboss::platform
