// 
// Copyright (c) 2022 by Cisco Systems, Inc.
// All rights reserved.
//
// This file was generated by gen_SensorConfig.py
// Do not modify!
//

#include <string>

namespace facebook::fboss::platform::sensor_service {

std::string getLassenConfig() {
  return R"json(
{
    "sensorMapList": {
        "CPU_CARD": {
            "12V_CPU_INA_IOUT": {
                "compute": "(@ * 131072) / 1000 / 2060",
                "path": "/run/devmap/sensors/12V_CPU_INA_IOUT/in10_input",
                "type": 2
            },
            "12V_GB_INA_IOUT": {
                "compute": "(@ * 131072) / 1000 / 2060",
                "path": "/run/devmap/sensors/12V_GB_INA_IOUT/in9_input",
                "type": 2
            },
            "12V_GEN_INA_IOUT": {
                "compute": "(@ * 131072) / 1000 / 2060",
                "path": "/run/devmap/sensors/12V_GEN_INA_IOUT/in11_input",
                "type": 2
            },
            "12V_QSFP_L_INA_IOUT": {
                "compute": "(@ * 131072) / 1000 / 2060",
                "path": "/run/devmap/sensors/12V_QSFP_L_INA_IOUT/in8_input",
                "type": 2
            },
            "12V_QSFP_R_IOUT": {
                "compute": "(@ * 131072) / 1000 / 2060",
                "path": "/run/devmap/sensors/12V_QSFP_R_IOUT/in12_input",
                "type": 2
            },
            "1V05_IO_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/1V05_IO_CURRENT/curr3_input",
                "thresholdMap": {
                    "0": 5,
                    "2": 7,
                    "4": 9
                },
                "type": 2
            },
            "1V05_SUS_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/1V05_SUS_CURRENT/curr3_input",
                "thresholdMap": {
                    "0": 5,
                    "2": 7,
                    "4": 9
                },
                "type": 2
            },
            "A1V": {
                "compute": "(@ * 131072) * 0.000017445813 / 2060",
                "path": "/run/devmap/sensors/A1V/in5_input",
                "thresholdMap": {
                    "0": 1.08,
                    "1": 0.92,
                    "2": 1.09,
                    "3": 0.91,
                    "4": 1.1,
                    "5": 0.9
                },
                "type": 1
            },
            "A1V2": {
                "compute": "(@ * 131072) * 0.000021039852 / 2060",
                "path": "/run/devmap/sensors/A1V2/in9_input",
                "thresholdMap": {
                    "0": 1.296,
                    "1": 1.104,
                    "2": 1.308,
                    "3": 1.092,
                    "4": 1.32,
                    "5": 1.08
                },
                "type": 1
            },
            "A1V21": {
                "compute": "(@ * 131072) * 0.000020934768 / 2060",
                "path": "/run/devmap/sensors/A1V2/in9_input",
                "thresholdMap": {
                    "0": 1.296,
                    "1": 1.104,
                    "2": 1.308,
                    "3": 1.092,
                    "4": 1.32,
                    "5": 1.08
                },
                "type": 1
            },
            "A1V8": {
                "compute": "(@ * 131072) * 0.000031433585 / 2060",
                "path": "/run/devmap/sensors/A1V8/in6_input",
                "thresholdMap": {
                    "0": 1.9440000000000002,
                    "1": 1.6560000000000001,
                    "2": 1.9620000000000002,
                    "3": 1.6380000000000001,
                    "4": 1.9800000000000002,
                    "5": 1.62
                },
                "type": 1
            },
            "A2V5": {
                "compute": "(@ * 131072) * 0.000043657757 / 2060",
                "path": "/run/devmap/sensors/A2V5/in8_input",
                "thresholdMap": {
                    "0": 2.7,
                    "1": 2.3000000000000003,
                    "2": 2.725,
                    "3": 2.275,
                    "4": 2.75,
                    "5": 2.25
                },
                "type": 1
            },
            "A3V3": {
                "compute": "(@ * 131072) * 0.000057936412 / 2060",
                "path": "/run/devmap/sensors/A3V3/in7_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "A3V31": {
                "compute": "(@ * 131072) * 0.000057628239 / 2060",
                "path": "/run/devmap/sensors/A3V3/in10_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "ACPI": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/ACPI/temp1_input",
                "type": 3
            },
            "CPU_CORE_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/CPU_CORE_CURRENT/curr2_input",
                "thresholdMap": {
                    "0": 12,
                    "2": 15,
                    "4": 18
                },
                "type": 2
            },
            "CPU_CORE_TEMP_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/CPU_CORE_TEMP_1/temp3_input",
                "thresholdMap": {
                    "0": 98,
                    "1": 5,
                    "2": 100,
                    "3": 0,
                    "4": 105,
                    "5": -10
                },
                "type": 3
            },
            "CPU_CORE_TEMP_2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/CPU_CORE_TEMP_2/temp4_input",
                "thresholdMap": {
                    "0": 98,
                    "1": 5,
                    "2": 100,
                    "3": 0,
                    "4": 105,
                    "5": -10
                },
                "type": 3
            },
            "CPU_CORE_TEMP_3": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/CPU_CORE_TEMP_3/temp5_input",
                "thresholdMap": {
                    "0": 98,
                    "1": 5,
                    "2": 100,
                    "3": 0,
                    "4": 105,
                    "5": -10
                },
                "type": 3
            },
            "CPU_PKG_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/CPU_PKG_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 98,
                    "1": 5,
                    "2": 100,
                    "3": 0,
                    "4": 105,
                    "5": -10
                },
                "type": 3
            },
            "CPU_U117_P1P05V_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/CPU_U117_P1P05V_TEMP/temp2_input",
                "thresholdMap": {
                    "0": 130,
                    "1": 5,
                    "2": 135,
                    "3": 0,
                    "4": 140,
                    "5": -10
                },
                "type": 3
            },
            "CPU_U17_P1P05V_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/CPU_U17_P1P05V_TEMP/temp2_input",
                "thresholdMap": {
                    "0": 130,
                    "1": 5,
                    "2": 135,
                    "3": 0,
                    "4": 140,
                    "5": -10
                },
                "type": 3
            },
            "DDR4_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/DDR4_CURRENT/curr2_input",
                "thresholdMap": {
                    "0": 12,
                    "2": 15,
                    "4": 18
                },
                "type": 2
            },
            "GB_HBM_VPP": {
                "compute": "(@ * 131072) * 0.000043677379 / 2060",
                "path": "/run/devmap/sensors/GB_HBM_VPP/in1_input",
                "thresholdMap": {
                    "0": 2.7,
                    "1": 2.3000000000000003,
                    "2": 2.725,
                    "3": 2.275,
                    "4": 2.75,
                    "5": 2.25
                },
                "type": 1
            },
            "GB_P1V8_PLLVDD": {
                "compute": "(@ * 131072) * 0.000031433585 / 2060",
                "path": "/run/devmap/sensors/GB_P1V8_PLLVDD/in2_input",
                "thresholdMap": {
                    "0": 1.9440000000000002,
                    "1": 1.6560000000000001,
                    "2": 1.9620000000000002,
                    "3": 1.6380000000000001,
                    "4": 1.9800000000000002,
                    "5": 1.62
                },
                "type": 1
            },
            "GB_P1V8_VDDIO": {
                "compute": "(@ * 131072) * 0.000031433585 / 2060",
                "path": "/run/devmap/sensors/GB_P1V8_VDDIO/in3_input",
                "thresholdMap": {
                    "0": 1.9440000000000002,
                    "1": 1.6560000000000001,
                    "2": 1.9620000000000002,
                    "3": 1.6380000000000001,
                    "4": 1.9800000000000002,
                    "5": 1.62
                },
                "type": 1
            },
            "GB_PCIE_VDDACK": {
                "compute": "(@ * 131072) * 0.000015716793 / 2060",
                "path": "/run/devmap/sensors/GB_PCIE_VDDACK/in13_input",
                "thresholdMap": {
                    "0": 0.8099999999999999,
                    "1": 0.69,
                    "2": 0.8175,
                    "3": 0.6825,
                    "4": 0.825,
                    "5": 0.6749999999999999
                },
                "type": 1
            },
            "GB_PCIE_VDDH": {
                "compute": "(@ * 131072) * 0.000020938318 / 2060",
                "path": "/run/devmap/sensors/GB_PCIE_VDDH/in14_input",
                "thresholdMap": {
                    "0": 1.296,
                    "1": 1.104,
                    "2": 1.308,
                    "3": 1.092,
                    "4": 1.32,
                    "5": 1.08
                },
                "type": 1
            },
            "MEZZ_5V": {
                "compute": "(@ * 131072) * 0.000088585558 / 2060",
                "path": "/run/devmap/sensors/MEZZ_5V/in1_input",
                "thresholdMap": {
                    "0": 5.4,
                    "1": 4.6000000000000005,
                    "2": 5.45,
                    "3": 4.55,
                    "4": 5.5,
                    "5": 4.5
                },
                "type": 1
            },
            "MEZZ_A3V3": {
                "compute": "(@ * 131072) * 0.000057628239 / 2060",
                "path": "/run/devmap/sensors/MEZZ_A3V3/in7_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "MEZZ_P3V3": {
                "compute": "(@ * 131072) * 0.000057628239 / 2060",
                "path": "/run/devmap/sensors/MEZZ_P3V3/in2_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "NP0_CORE": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_CORE/power1_input",
                "type": 0
            },
            "NP0_CORE1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_CORE/in2_input",
                "thresholdMap": {
                    "0": 0.891,
                    "1": 0.759,
                    "2": 0.89925,
                    "3": 0.75075,
                    "4": 0.9075000000000001,
                    "5": 0.7425
                },
                "type": 1
            },
            "NP0_CORE2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_CORE/curr1_input",
                "type": 2
            },
            "NP0_CORE_I": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_CORE_I/temp1_input",
                "thresholdMap": {
                    "4": 104
                },
                "type": 3
            },
            "NP0_CORE_O": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_CORE_O/power2_input",
                "type": 0
            },
            "NP0_HBM_VDD": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_HBM_VDD/power3_input",
                "type": 0
            },
            "NP0_HBM_VDD1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_HBM_VDD/in3_input",
                "thresholdMap": {
                    "0": 1.296,
                    "1": 1.104,
                    "2": 1.308,
                    "3": 1.092,
                    "4": 1.32,
                    "5": 1.08
                },
                "type": 1
            },
            "NP0_HBM_VDD2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_HBM_VDD/curr2_input",
                "type": 2
            },
            "NP0_HBM_VDD_E": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_HBM_VDD_E/temp2_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "NP0_HBM_VDD_O": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_HBM_VDD_O/power4_input",
                "type": 0
            },
            "NP0_IFG_VDDA": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDA/power3_input",
                "type": 0
            },
            "NP0_IFG_VDDA1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDA/in3_input",
                "thresholdMap": {
                    "0": 1.0151999999999999,
                    "1": 0.8647999999999999,
                    "2": 1.0246,
                    "3": 0.8553999999999998,
                    "4": 1.0339999999999998,
                    "5": 0.8459999999999999
                },
                "type": 1
            },
            "NP0_IFG_VDDA2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDA/curr2_input",
                "type": 2
            },
            "NP0_IFG_VDDA_E": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDA_E/temp2_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "NP0_IFG_VDDA_O": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDA_O/power4_input",
                "type": 0
            },
            "NP0_IFG_VDDCK": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDCK/power1_input",
                "type": 0
            },
            "NP0_IFG_VDDCK1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDCK/in2_input",
                "thresholdMap": {
                    "0": 1.242,
                    "1": 1.058,
                    "2": 1.2535,
                    "3": 1.0465,
                    "4": 1.265,
                    "5": 1.035
                },
                "type": 1
            },
            "NP0_IFG_VDDCK2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDCK/curr1_input",
                "type": 2
            },
            "NP0_IFG_VDDCK_E": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDCK_E/temp1_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "NP0_IFG_VDDCK_O": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDCK_O/power2_input",
                "type": 0
            },
            "NP0_IFG_VDDS": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDS/power1_input",
                "type": 0
            },
            "NP0_IFG_VDDS1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDS/in2_input",
                "thresholdMap": {
                    "0": 0.8099999999999999,
                    "1": 0.69,
                    "2": 0.8175,
                    "3": 0.6825,
                    "4": 0.825,
                    "5": 0.6749999999999999
                },
                "type": 1
            },
            "NP0_IFG_VDDS2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDS/curr1_input",
                "type": 2
            },
            "NP0_IFG_VDDS_E": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDS_E/temp1_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "NP0_IFG_VDDS_O": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/NP0_IFG_VDDS_O/power2_input",
                "type": 0
            },
            "OUTLET_SENSOR": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/OUTLET_SENSOR/temp1_input",
                "thresholdMap": {
                    "0": 41,
                    "2": 45,
                    "4": 47
                },
                "type": 3
            },
            "P12V": {
                "compute": "(@ * 131072) * 0.000208808815 / 2060",
                "path": "/run/devmap/sensors/P12V/in10_input",
                "thresholdMap": {
                    "0": 12.959999999999999,
                    "1": 11.04,
                    "2": 13.08,
                    "3": 10.92,
                    "4": 13.2,
                    "5": 10.799999999999999
                },
                "type": 1
            },
            "P12V0_E_MB_2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P12V0_E_MB_2/in1_input",
                "thresholdMap": {
                    "0": 12.959999999999999,
                    "1": 11.04,
                    "2": 13.08,
                    "3": 10.92,
                    "4": 13.2,
                    "5": 10.799999999999999
                },
                "type": 1
            },
            "P12V0_E_MB_21": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P12V0_E_MB_2/in1_input",
                "thresholdMap": {
                    "0": 12.959999999999999,
                    "1": 11.04,
                    "2": 13.08,
                    "3": 10.92,
                    "4": 13.2,
                    "5": 10.799999999999999
                },
                "type": 1
            },
            "P12V0_NPU_CORE_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P12V0_NPU_CORE_1/in1_input",
                "thresholdMap": {
                    "0": 12.959999999999999,
                    "1": 11.04,
                    "2": 13.08,
                    "3": 10.92,
                    "4": 13.2,
                    "5": 10.799999999999999
                },
                "type": 1
            },
            "P12V0_NPU_CORE_2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P12V0_NPU_CORE_2/in1_input",
                "thresholdMap": {
                    "0": 12.959999999999999,
                    "1": 11.04,
                    "2": 13.08,
                    "3": 10.92,
                    "4": 13.2,
                    "5": 10.799999999999999
                },
                "type": 1
            },
            "P12V0_NPU_CORE_3": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P12V0_NPU_CORE_3/in1_input",
                "thresholdMap": {
                    "0": 12.959999999999999,
                    "1": 11.04,
                    "2": 13.08,
                    "3": 10.92,
                    "4": 13.2,
                    "5": 10.799999999999999
                },
                "type": 1
            },
            "P12V_STBY": {
                "compute": "(@ * 131072) * 0.000208808815 / 2060",
                "path": "/run/devmap/sensors/P12V_STBY/in1_input",
                "thresholdMap": {
                    "0": 12.959999999999999,
                    "1": 11.04,
                    "2": 13.08,
                    "3": 10.92,
                    "4": 13.2,
                    "5": 10.799999999999999
                },
                "type": 1
            },
            "P1V05_COMBINED_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P1V05_COMBINED_1/in3_input",
                "thresholdMap": {
                    "0": 1.1340000000000001,
                    "1": 0.9660000000000001,
                    "2": 1.1445,
                    "3": 0.9555,
                    "4": 1.155,
                    "5": 0.9450000000000001
                },
                "type": 1
            },
            "P1V05_VCCSCSUS_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P1V05_VCCSCSUS_1/in3_input",
                "thresholdMap": {
                    "0": 1.1340000000000001,
                    "1": 0.9660000000000001,
                    "2": 1.1445,
                    "3": 0.9555,
                    "4": 1.155,
                    "5": 0.9450000000000001
                },
                "type": 1
            },
            "P1V2_VDDQ_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P1V2_VDDQ_1/in2_input",
                "thresholdMap": {
                    "0": 1.296,
                    "1": 1.104,
                    "2": 1.308,
                    "3": 1.092,
                    "4": 1.32,
                    "5": 1.08
                },
                "type": 1
            },
            "P1V8": {
                "compute": "(@ * 131072) * 0.000031433585 / 2060",
                "path": "/run/devmap/sensors/P1V8/in12_input",
                "thresholdMap": {
                    "0": 1.9440000000000002,
                    "1": 1.6560000000000001,
                    "2": 1.9620000000000002,
                    "3": 1.6380000000000001,
                    "4": 1.9800000000000002,
                    "5": 1.62
                },
                "type": 1
            },
            "P3V3": {
                "compute": "(@ * 131072) * 0.000057628239 / 2060",
                "path": "/run/devmap/sensors/P3V3/in7_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "P3V3_L": {
                "compute": "(@ * 131072) * 0.000057628239 / 2060",
                "path": "/run/devmap/sensors/P3V3_L/in11_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "P3V3_QSFP_L_MB": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/P3V3_QSFP_L_MB/power1_input",
                "type": 0
            },
            "P3V3_QSFP_L_MB1": {
                "compute": "@*2/1000",
                "path": "/run/devmap/sensors/P3V3_QSFP_L_MB/in2_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 2.97,
                    "2": 3.597,
                    "3": 2.805,
                    "4": 3.63,
                    "5": 2.64
                },
                "type": 1
            },
            "P3V3_QSFP_L_MB2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P3V3_QSFP_L_MB/curr7_input",
                "type": 2
            },
            "P3V3_QSFP_L_MB_E": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P3V3_QSFP_L_MB_E/temp1_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "P3V3_QSFP_L_MB_O": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/P3V3_QSFP_L_MB_O/power2_input",
                "type": 0
            },
            "P3V3_QSFP_R_MB": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/P3V3_QSFP_R_MB/power1_input",
                "type": 0
            },
            "P3V3_QSFP_R_MB1": {
                "compute": "@*2/1000",
                "path": "/run/devmap/sensors/P3V3_QSFP_R_MB/in2_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 2.97,
                    "2": 3.597,
                    "3": 2.805,
                    "4": 3.63,
                    "5": 2.64
                },
                "type": 1
            },
            "P3V3_QSFP_R_MB2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P3V3_QSFP_R_MB/curr1_input",
                "type": 2
            },
            "P3V3_QSFP_R_MB_E": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/P3V3_QSFP_R_MB_E/temp1_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "P3V3_QSFP_R_MB_O": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/P3V3_QSFP_R_MB_O/power2_input",
                "type": 0
            },
            "P3V3_R": {
                "compute": "(@ * 131072) * 0.000057628239 / 2060",
                "path": "/run/devmap/sensors/P3V3_R/in4_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "P5V": {
                "compute": "(@ * 131072) * 0.000087667980 / 2060",
                "path": "/run/devmap/sensors/P5V/in8_input",
                "thresholdMap": {
                    "0": 5.4,
                    "1": 4.6000000000000005,
                    "2": 5.45,
                    "3": 4.55,
                    "4": 5.5,
                    "5": 4.5
                },
                "type": 1
            },
            "PHY_0V8_VDD": {
                "compute": "(@ * 131072) * 0.000015716793 / 2060",
                "path": "/run/devmap/sensors/PHY_0V8_VDD/in6_input",
                "thresholdMap": {
                    "0": 0.864,
                    "1": 0.736,
                    "2": 0.872,
                    "3": 0.728,
                    "4": 0.88,
                    "5": 0.72
                },
                "type": 1
            },
            "PMOD_P0V6_VTT_DIMM": {
                "compute": "(@ * 131072) * 0.000031433585 / 2060",
                "path": "/run/devmap/sensors/PMOD_P0V6_VTT_DIMM/in12_input",
                "thresholdMap": {
                    "0": 0.648,
                    "1": 0.552,
                    "2": 0.654,
                    "3": 0.546,
                    "4": 0.66,
                    "5": 0.54
                },
                "type": 1
            },
            "PMOD_P1V5_PCH": {
                "compute": "(@ * 131072) * 0.000026164632 / 2060",
                "path": "/run/devmap/sensors/PMOD_P1V5_PCH/in11_input",
                "thresholdMap": {
                    "0": 1.6199999999999999,
                    "1": 1.38,
                    "2": 1.635,
                    "3": 1.365,
                    "4": 1.65,
                    "5": 1.3499999999999999
                },
                "type": 1
            },
            "PMOD_P2V5_VPP_VSENSE": {
                "compute": "(@ * 131072) * 0.000043657757 / 2060",
                "path": "/run/devmap/sensors/PMOD_P2V5_VPP_VSENSE/in5_input",
                "thresholdMap": {
                    "0": 2.7,
                    "1": 2.3000000000000003,
                    "2": 2.725,
                    "3": 2.275,
                    "4": 2.75,
                    "5": 2.25
                },
                "type": 1
            },
            "PMOD_P3V3_CPU": {
                "compute": "(@ * 131072) * 0.000057936412 / 2060",
                "path": "/run/devmap/sensors/PMOD_P3V3_CPU/in4_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "PMOD_P3V3_PCH": {
                "compute": "(@ * 131072) * 0.000057936412 / 2060",
                "path": "/run/devmap/sensors/PMOD_P3V3_PCH/in3_input",
                "thresholdMap": {
                    "0": 3.564,
                    "1": 3.036,
                    "2": 3.597,
                    "3": 3.003,
                    "4": 3.6300000000000003,
                    "5": 2.97
                },
                "type": 1
            },
            "PMOD_P5V": {
                "compute": "(@ * 131072) * 0.000087212790 / 2060",
                "path": "/run/devmap/sensors/PMOD_P5V/in13_input",
                "thresholdMap": {
                    "0": 5.4,
                    "1": 4.6000000000000005,
                    "2": 5.45,
                    "3": 4.55,
                    "4": 5.5,
                    "5": 4.5
                },
                "type": 1
            },
            "PMOD_PVCCKRHV": {
                "compute": "(@ * 131072) * 0.000022662118 / 2060",
                "path": "/run/devmap/sensors/PMOD_PVCCKRHV/in2_input",
                "thresholdMap": {
                    "0": 1.4040000000000001,
                    "1": 1.1960000000000002,
                    "2": 1.417,
                    "3": 1.183,
                    "4": 1.4300000000000002,
                    "5": 1.1700000000000002
                },
                "type": 1
            },
            "PMOD_PVCCSCFUSESUS": {
                "compute": "(@ * 131072) * 0.000029669037 / 2060",
                "path": "/run/devmap/sensors/PMOD_PVCCSCFUSESUS/in6_input",
                "thresholdMap": {
                    "0": 1.836,
                    "1": 1.564,
                    "2": 1.8530000000000002,
                    "3": 1.5470000000000002,
                    "4": 1.87,
                    "5": 1.53
                },
                "type": 1
            },
            "POL_0X5A_TEMP2_INPUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/POL_0X5A_TEMP2_INPUT/temp2_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "POL_0X5B_TEMP2_INPUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/POL_0X5B_TEMP2_INPUT/temp2_input",
                "thresholdMap": {
                    "4": 115
                },
                "type": 3
            },
            "PU_COORE_TEMP_0": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PU_COORE_TEMP_0/temp2_input",
                "thresholdMap": {
                    "0": 98,
                    "1": 5,
                    "2": 100,
                    "3": 0,
                    "4": 105,
                    "5": -10
                },
                "type": 3
            },
            "PVCCIN_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PVCCIN_1/in2_input",
                "thresholdMap": {
                    "0": 1.9440000000000002,
                    "1": 1.6560000000000001,
                    "2": 1.9620000000000002,
                    "3": 1.6380000000000001,
                    "4": 1.9800000000000002,
                    "5": 1.62
                },
                "type": 1
            },
            "PWR_PHY_AVDD1P5": {
                "compute": "(@ * 131072) * 0.000026194654 / 2060",
                "path": "/run/devmap/sensors/PWR_PHY_AVDD1P5/in5_input",
                "thresholdMap": {
                    "0": 1.6199999999999999,
                    "1": 1.38,
                    "2": 1.635,
                    "3": 1.365,
                    "4": 1.65,
                    "5": 1.3499999999999999
                },
                "type": 1
            },
            "PWR_PHY_AVDD2P0": {
                "compute": "(@ * 131072) * 0.000034764296 / 2060",
                "path": "/run/devmap/sensors/PWR_PHY_AVDD2P0/in4_input",
                "thresholdMap": {
                    "0": 2.16,
                    "1": 1.84,
                    "2": 2.18,
                    "3": 1.82,
                    "4": 2.2,
                    "5": 1.8
                },
                "type": 1
            },
            "PWR_PHY_AVDD2P5": {
                "compute": "(@ * 131072) * 0.000043640803 / 2060",
                "path": "/run/devmap/sensors/PWR_PHY_AVDD2P5/in3_input",
                "thresholdMap": {
                    "0": 2.7,
                    "1": 2.3000000000000003,
                    "2": 2.725,
                    "3": 2.275,
                    "4": 2.75,
                    "5": 2.25
                },
                "type": 1
            },
            "RDIMM_0_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/RDIMM_0_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 93,
                    "1": 0,
                    "2": 95,
                    "3": -5,
                    "4": 100,
                    "5": -10
                },
                "type": 3
            },
            "RDIMM_1_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/RDIMM_1_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 93,
                    "1": 0,
                    "2": 95,
                    "3": -5,
                    "4": 100,
                    "5": -10
                },
                "type": 3
            },
            "TI_1PLUS1_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TI_1PLUS1_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 130,
                    "1": 5,
                    "2": 135,
                    "3": 0,
                    "4": 140,
                    "5": -10
                },
                "type": 3
            },
            "TI_2PLUS1_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TI_2PLUS1_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 130,
                    "1": 5,
                    "2": 135,
                    "3": 0,
                    "4": 140,
                    "5": -10
                },
                "type": 3
            },
            "TMP421_LOCAL_BB": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TMP421_LOCAL_BB/temp1_input",
                "thresholdMap": {
                    "0": 45,
                    "1": -5,
                    "2": 50,
                    "3": -10,
                    "4": 55,
                    "5": -15
                },
                "type": 3
            },
            "TMP421_REMOTE_BB": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TMP421_REMOTE_BB/temp2_input",
                "thresholdMap": {
                    "0": 45,
                    "1": -5,
                    "2": 50,
                    "3": -10,
                    "4": 55,
                    "5": -15
                },
                "type": 3
            },
            "TPS53659_58_CURR1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TPS53659_58_CURR1/curr1_input",
                "type": 2
            },
            "TPS53659_58_IN1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TPS53659_58_IN1/in1_input",
                "type": 1
            },
            "TPS53659_58_POWER1": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/TPS53659_58_POWER1/power1_input",
                "type": 0
            },
            "TPS53659_58_POWER2": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/TPS53659_58_POWER2/power2_input",
                "type": 0
            },
            "TPS53659_58_POWER3": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/TPS53659_58_POWER3/power3_input",
                "type": 0
            },
            "TPS53659_59_CURR1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TPS53659_59_CURR1/curr1_input",
                "type": 2
            },
            "TPS53659_59_IN1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/TPS53659_59_IN1/in1_input",
                "type": 1
            },
            "TPS53659_59_POWER1": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/TPS53659_59_POWER1/power1_input",
                "type": 0
            },
            "TPS53659_59_POWER2": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/TPS53659_59_POWER2/power2_input",
                "type": 0
            },
            "TPS53659_59_POWER3": {
                "compute": "@/1000000",
                "path": "/run/devmap/sensors/TPS53659_59_POWER3/power3_input",
                "type": 0
            }
        },
        "FANTRAY1": {
            "FANTRAY1_FAN0_PWM": {
                "path": "/run/devmap/sensors/FANTRAY1_FAN0/pwm11",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY1_FAN0_RPM": {
                "path": "/run/devmap/sensors/FANTRAY1_FAN0/fan11_input",
                "thresholdMap": {
                    "0": 31750,
                    "1": 9982,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "FANTRAY1_FAN1_PWM": {
                "path": "/run/devmap/sensors/FANTRAY1_FAN1/pwm12",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY1_FAN1_RPM": {
                "path": "/run/devmap/sensors/FANTRAY1_FAN1/fan12_input",
                "thresholdMap": {
                    "0": 28750,
                    "1": 8820,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "FANTRAY2": {
            "FANTRAY2_FAN0_PWM": {
                "path": "/run/devmap/sensors/FANTRAY2_FAN0/pwm9",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY2_FAN0_RPM": {
                "path": "/run/devmap/sensors/FANTRAY2_FAN0/fan9_input",
                "thresholdMap": {
                    "0": 31750,
                    "1": 9982,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "FANTRAY2_FAN1_PWM": {
                "path": "/run/devmap/sensors/FANTRAY2_FAN1/pwm10",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY2_FAN1_RPM": {
                "path": "/run/devmap/sensors/FANTRAY2_FAN1/fan10_input",
                "thresholdMap": {
                    "0": 28750,
                    "1": 8820,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "FANTRAY3": {
            "FANTRAY3_FAN0_PWM": {
                "path": "/run/devmap/sensors/FANTRAY3_FAN0/pwm7",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY3_FAN0_RPM": {
                "path": "/run/devmap/sensors/FANTRAY3_FAN0/fan7_input",
                "thresholdMap": {
                    "0": 31750,
                    "1": 9982,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "FANTRAY3_FAN1_PWM": {
                "path": "/run/devmap/sensors/FANTRAY3_FAN1/pwm8",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY3_FAN1_RPM": {
                "path": "/run/devmap/sensors/FANTRAY3_FAN1/fan8_input",
                "thresholdMap": {
                    "0": 28750,
                    "1": 8820,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "FANTRAY4": {
            "FANTRAY4_FAN0_PWM": {
                "path": "/run/devmap/sensors/FANTRAY4_FAN0/pwm5",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY4_FAN0_RPM": {
                "path": "/run/devmap/sensors/FANTRAY4_FAN0/fan5_input",
                "thresholdMap": {
                    "0": 31750,
                    "1": 9982,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "FANTRAY4_FAN1_PWM": {
                "path": "/run/devmap/sensors/FANTRAY4_FAN1/pwm6",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY4_FAN1_RPM": {
                "path": "/run/devmap/sensors/FANTRAY4_FAN1/fan6_input",
                "thresholdMap": {
                    "0": 28750,
                    "1": 8820,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "FANTRAY5": {
            "FANTRAY5_FAN0_PWM": {
                "path": "/run/devmap/sensors/FANTRAY5_FAN0/pwm3",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY5_FAN0_RPM": {
                "path": "/run/devmap/sensors/FANTRAY5_FAN0/fan3_input",
                "thresholdMap": {
                    "0": 31750,
                    "1": 9982,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "FANTRAY5_FAN1_PWM": {
                "path": "/run/devmap/sensors/FANTRAY5_FAN1/pwm4",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY5_FAN1_RPM": {
                "path": "/run/devmap/sensors/FANTRAY5_FAN1/fan4_input",
                "thresholdMap": {
                    "0": 28750,
                    "1": 8820,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "FANTRAY6": {
            "FANTRAY6_FAN0_PWM": {
                "path": "/run/devmap/sensors/FANTRAY6_FAN0/pwm1",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY6_FAN0_RPM": {
                "path": "/run/devmap/sensors/FANTRAY6_FAN0/fan1_input",
                "thresholdMap": {
                    "0": 31750,
                    "1": 9982,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "FANTRAY6_FAN1_PWM": {
                "path": "/run/devmap/sensors/FANTRAY6_FAN1/pwm2",
                "thresholdMap": {
                    "0": 100,
                    "1": 40
                },
                "type": 5
            },
            "FANTRAY6_FAN1_RPM": {
                "path": "/run/devmap/sensors/FANTRAY6_FAN1/fan2_input",
                "thresholdMap": {
                    "0": 28750,
                    "1": 8820,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "PSU0_PEM0": {
            "PSU0_BUS_VOLTAGE": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_BUS_VOLTAGE/in0_input",
                "type": 1
            },
            "PSU0_HTSW_12VS_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12VS_CURRENT/curr1_input",
                "type": 2
            },
            "PSU0_HTSW_12VS_IN1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12VS_IN1/in1_input",
                "type": 1
            },
            "PSU0_HTSW_12VS_IN2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12VS_IN2/in2_input",
                "type": 1
            },
            "PSU0_HTSW_12VS_POWER": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12VS_POWER/power1_input",
                "type": 0
            },
            "PSU0_HTSW_12VS_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12VS_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_HTSW_12V_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12V_CURRENT/curr1_input",
                "type": 2
            },
            "PSU0_HTSW_12V_IN1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12V_IN1/in1_input",
                "type": 1
            },
            "PSU0_HTSW_12V_IN2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12V_IN2/in2_input",
                "type": 1
            },
            "PSU0_HTSW_12V_POWER": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12V_POWER/power1_input",
                "type": 0
            },
            "PSU0_HTSW_12V_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_HTSW_12V_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_MAX_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_MAX_TEMP/max_temp",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP1/temp1_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP2/temp2_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP3": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP3/temp3_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP4": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP4/temp4_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP5": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP5/temp5_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP6": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP6/temp6_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP7": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP7/temp7_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU0_TEMP8": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP8/temp8_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            }
        },
        "PSU0_PEM0_PSU0_FAN": {
            "PSU0_FAN1_PWM": {
                "path": "/run/devmap/sensors/PSU0_FAN1/pwm1",
                "thresholdMap": {
                    "0": 100,
                    "1": 10
                },
                "type": 5
            },
            "PSU0_FAN1_RPM": {
                "path": "/run/devmap/sensors/PSU0_FAN1/fan1_input",
                "thresholdMap": {
                    "0": 31000,
                    "1": 4123,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "PSU0_FAN2_PWM": {
                "path": "/run/devmap/sensors/PSU0_FAN2/pwm1",
                "thresholdMap": {
                    "0": 100,
                    "1": 10
                },
                "type": 5
            },
            "PSU0_FAN2_RPM": {
                "path": "/run/devmap/sensors/PSU0_FAN2/fan2_input",
                "thresholdMap": {
                    "0": 31000,
                    "1": 4123,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "PSU0_VARIATION": {
            "PSU00_IIN": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU00_IIN/curr1_input",
                "type": 2
            },
            "PSU00_IOUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU00_IOUT/curr2_input",
                "type": 2
            },
            "PSU00_PIN": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU00_PIN/power2_input",
                "type": 0
            },
            "PSU00_POUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU00_POUT/power1_input",
                "type": 0
            },
            "PSU0_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 71,
                    "2": 72,
                    "4": 73
                },
                "type": 3
            },
            "PSU0_TEMP1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 71,
                    "2": 72,
                    "4": 73
                },
                "type": 3
            },
            "PSU0_TEMP_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP_1/temp1_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 66,
                    "3": -5,
                    "4": 70,
                    "5": -10
                },
                "type": 3
            },
            "PSU0_TEMP_2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP_2/temp2_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 85,
                    "3": -5,
                    "4": 90,
                    "5": -10
                },
                "type": 3
            },
            "PSU0_TEMP_3": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP_3/temp3_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 85,
                    "3": -5,
                    "4": 90,
                    "5": -10
                },
                "type": 3
            },
            "PSU0_TEMP_4": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_TEMP_4/temp4_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 85,
                    "3": -5,
                    "4": 90,
                    "5": -10
                },
                "type": 3
            },
            "PSU0_VIN": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_VIN/in1_input",
                "thresholdMap": {
                    "0": 244,
                    "1": 200,
                    "2": 254,
                    "3": 190,
                    "4": 264,
                    "5": 180
                },
                "type": 1
            },
            "PSU0_VOUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU0_VOUT/in2_input",
                "thresholdMap": {
                    "0": 13.2,
                    "1": 10.799999999999999,
                    "2": 13.799999999999999,
                    "3": 10.2,
                    "4": 14.399999999999999,
                    "5": 9.6
                },
                "type": 1
            }
        },
        "PSU1_PEM1": {
            "PSU1_BUS_VOLTAGE": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_BUS_VOLTAGE/in0_input",
                "type": 1
            },
            "PSU1_HTSW_12VS_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12VS_CURRENT/curr1_input",
                "type": 2
            },
            "PSU1_HTSW_12VS_IN1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12VS_IN1/in1_input",
                "type": 1
            },
            "PSU1_HTSW_12VS_IN2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12VS_IN2/in2_input",
                "type": 1
            },
            "PSU1_HTSW_12VS_POWER": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12VS_POWER/power1_input",
                "type": 0
            },
            "PSU1_HTSW_12VS_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12VS_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_HTSW_12V_CURRENT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12V_CURRENT/curr1_input",
                "type": 2
            },
            "PSU1_HTSW_12V_IN1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12V_IN1/in1_input",
                "type": 1
            },
            "PSU1_HTSW_12V_IN2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12V_IN2/in2_input",
                "type": 1
            },
            "PSU1_HTSW_12V_POWER": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12V_POWER/power1_input",
                "type": 0
            },
            "PSU1_HTSW_12V_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_HTSW_12V_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_MAX_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_MAX_TEMP/max_temp",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP1/temp1_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP2/temp2_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP3": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP3/temp3_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP4": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP4/temp4_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP5": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP5/temp5_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP6": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP6/temp6_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP7": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP7/temp7_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            },
            "PSU1_TEMP8": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP8/temp8_input",
                "thresholdMap": {
                    "0": 90,
                    "2": 93,
                    "4": 97
                },
                "type": 3
            }
        },
        "PSU1_PEM1_PSU1_FAN": {
            "PSU1_FAN1_PWM": {
                "path": "/run/devmap/sensors/PSU1_FAN1/pwm1",
                "thresholdMap": {
                    "0": 100,
                    "1": 10
                },
                "type": 5
            },
            "PSU1_FAN1_RPM": {
                "path": "/run/devmap/sensors/PSU1_FAN1/fan1_input",
                "thresholdMap": {
                    "0": 31000,
                    "1": 4123,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            },
            "PSU1_FAN2_PWM": {
                "path": "/run/devmap/sensors/PSU1_FAN2/pwm1",
                "thresholdMap": {
                    "0": 100,
                    "1": 10
                },
                "type": 5
            },
            "PSU1_FAN2_RPM": {
                "path": "/run/devmap/sensors/PSU1_FAN2/fan2_input",
                "thresholdMap": {
                    "0": 31000,
                    "1": 4123,
                    "3": 100,
                    "5": 0
                },
                "type": 4
            }
        },
        "PSU1_VARIATION": {
            "PSU01_IIN": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU01_IIN/curr1_input",
                "type": 2
            },
            "PSU01_IOUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU01_IOUT/curr2_input",
                "type": 2
            },
            "PSU01_PIN": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU01_PIN/power2_input",
                "type": 0
            },
            "PSU01_POUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU01_POUT/power1_input",
                "type": 0
            },
            "PSU1_TEMP": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 71,
                    "2": 72,
                    "4": 73
                },
                "type": 3
            },
            "PSU1_TEMP1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP/temp1_input",
                "thresholdMap": {
                    "0": 71,
                    "2": 72,
                    "4": 73
                },
                "type": 3
            },
            "PSU1_TEMP_1": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP_1/temp1_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 66,
                    "3": -5,
                    "4": 70,
                    "5": -10
                },
                "type": 3
            },
            "PSU1_TEMP_2": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP_2/temp2_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 85,
                    "3": -5,
                    "4": 90,
                    "5": -10
                },
                "type": 3
            },
            "PSU1_TEMP_3": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP_3/temp3_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 85,
                    "3": -5,
                    "4": 90,
                    "5": -10
                },
                "type": 3
            },
            "PSU1_TEMP_4": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_TEMP_4/temp4_input",
                "thresholdMap": {
                    "1": 0,
                    "2": 85,
                    "3": -5,
                    "4": 90,
                    "5": -10
                },
                "type": 3
            },
            "PSU1_VIN": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_VIN/in1_input",
                "thresholdMap": {
                    "0": 244,
                    "1": 200,
                    "2": 254,
                    "3": 190,
                    "4": 264,
                    "5": 180
                },
                "type": 1
            },
            "PSU1_VOUT": {
                "compute": "@/1000",
                "path": "/run/devmap/sensors/PSU1_VOUT/in2_input",
                "thresholdMap": {
                    "0": 13.2,
                    "1": 10.799999999999999,
                    "2": 13.799999999999999,
                    "3": 10.2,
                    "4": 14.399999999999999,
                    "5": 9.6
                },
                "type": 1
            }
        }
    },
    "source": "sysfs"
}
  )json";

} // getLassenConfig()

} // namespace facebook::fboss::platform::sensor_service
