// 
// Copyright (c) 2022 by Cisco Systems, Inc.
// All rights reserved.
//
// This file was generated by gen_WeutilConfig.py
// Do not modify!
//

#include <string>

namespace facebook::fboss::platform {

std::string getSandiaIdpromsData() {
  return R"json({
    "idproms": [
        {
            "aliases": [
                "board"
            ],
            "match": [],
            "name": "BMC",
            "oid": {
                "index": 1,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:8:0x54]/eeprom"
        },
        {
            "aliases": [
                "idprom",
                "bootstrap",
                "Base_Board_IDPROM"
            ],
            "match": [],
            "name": "SCM",
            "oid": {
                "index": 2,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_IDPROM:0x50]/eeprom",
            "size": 512
        },
        {
            "aliases": [
                "chassis",
                "chassis_IDPROM",
                "Base_Board_IDPROM"
            ],
            "match": [],
            "name": "PDB",
            "oid": {
                "index": 3,
                "type": "idprom"
            },
            "parents": [
                {
                    "index": 1,
                    "type": "platform"
                }
            ],
            "path": "[i2c:SCM_IDPROM:0xa0d0]/eeprom",
            "size": 512
        }
    ],
    "pid": "85_SCM_O_BMC"
}
  )json";

} // getSandiaIdproms()

} // namespace facebook::fboss::platform
